//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlickrDownloader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlickrDownloader.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling downloads...please wait..
        /// </summary>
        internal static string DownloadsCanceled {
            get {
                return ResourceManager.GetString("DownloadsCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads Completed..
        /// </summary>
        internal static string DownloadsCompleted {
            get {
                return ResourceManager.GetString("DownloadsCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads paused..
        /// </summary>
        internal static string DownloadsPaused {
            get {
                return ResourceManager.GetString("DownloadsPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads is starting up again....
        /// </summary>
        internal static string DownloadsResume {
            get {
                return ResourceManager.GetString("DownloadsResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded {0} of {1}.
        /// </summary>
        internal static string DownloadStatus {
            get {
                return ResourceManager.GetString("DownloadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed too connect to the network.\r\n\r\nThis might happen if your firewall blocked the communication from Flickr Downloadr. Make sure you accept any dialog which asks for network permissions for FlickrDownloadr.exe.\r\n\r\nDo you want to try again?.
        /// </summary>
        internal static string ErrorNetworkAccess {
            get {
                return ResourceManager.GetString("ErrorNetworkAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Error.
        /// </summary>
        internal static string ErrorNetworkAccessTitle {
            get {
                return ResourceManager.GetString("ErrorNetworkAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source type of download you would like to use in your search.
        /// </summary>
        internal static string PageEveryoneDescription {
            get {
                return ResourceManager.GetString("PageEveryoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download by searching.
        /// </summary>
        internal static string PageEveryoneTitle {
            get {
                return ResourceManager.GetString("PageEveryoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source type of download you would like to use.
        /// </summary>
        internal static string PageGroupDescription {
            get {
                return ResourceManager.GetString("PageGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download by Groups.
        /// </summary>
        internal static string PageGroupTitle {
            get {
                return ResourceManager.GetString("PageGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the download options..
        /// </summary>
        internal static string PageOptionsDescription {
            get {
                return ResourceManager.GetString("PageOptionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Options.
        /// </summary>
        internal static string PageOptionsTitle {
            get {
                return ResourceManager.GetString("PageOptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview the photos you are about to download..
        /// </summary>
        internal static string PagePreviewDescription {
            get {
                return ResourceManager.GetString("PagePreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos Preview.
        /// </summary>
        internal static string PagePreviewTitle {
            get {
                return ResourceManager.GetString("PagePreviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the download options..
        /// </summary>
        internal static string PageProgressDescription {
            get {
                return ResourceManager.GetString("PageProgressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Options.
        /// </summary>
        internal static string PageProgressTitle {
            get {
                return ResourceManager.GetString("PageProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source type of download you would like to use.
        /// </summary>
        internal static string PageSourceDescription {
            get {
                return ResourceManager.GetString("PageSourceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr Downloader.
        /// </summary>
        internal static string PageSourceTitle {
            get {
                return ResourceManager.GetString("PageSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source type of download you would like to use.
        /// </summary>
        internal static string PageUserDescription {
            get {
                return ResourceManager.GetString("PageUserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download by User.
        /// </summary>
        internal static string PageUserTitle {
            get {
                return ResourceManager.GetString("PageUserTitle", resourceCulture);
            }
        }
    }
}
